/**
 * Scientifically reasonable demo dataset
 * Clearly marked as demo/sample data for demonstration purposes
 */

export const WASTE_TYPES = [
  'Coconut Shell',
  'Rice Husk',
  'Sawdust',
  'Sugarcane Bagasse',
  'Corn Cob',
  'Bamboo',
];

export const AGENTS = ['KOH', 'H₃PO₄', 'ZnCl₂', 'H₂SO₄'];

export const POLLUTANT_TYPES = [
  'Methylene Blue',
  'Crystal Violet',
  'Phenol',
  'Congo Red',
  'Lead (Pb²⁺)',
  'Chromium (Cr⁶⁺)',
  'Cadmium (Cd²⁺)',
];

/**
 * Demo experiment data — NOT real experimental results
 * Generated with scientifically plausible values for demonstration
 */
export const DEMO_EXPERIMENTS = [
  {
    id: 1,
    C0: 100,
    Ce: 12.5,
    V: 100,
    m: 0.5,
    pH: 6.0,
    contactTime: 60,
    adsorbentDose: 5.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Coconut Shell',
    agent: 'KOH',
    activationTemp: 700,
    activationTime: 120,
  },
  {
    id: 2,
    C0: 80,
    Ce: 18.0,
    V: 100,
    m: 0.5,
    pH: 5.0,
    contactTime: 45,
    adsorbentDose: 5.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Coconut Shell',
    agent: 'KOH',
    activationTemp: 700,
    activationTime: 120,
  },
  {
    id: 3,
    C0: 120,
    Ce: 8.4,
    V: 100,
    m: 1.0,
    pH: 7.0,
    contactTime: 90,
    adsorbentDose: 10.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Coconut Shell',
    agent: 'KOH',
    activationTemp: 700,
    activationTime: 120,
  },
  {
    id: 4,
    C0: 150,
    Ce: 25.0,
    V: 100,
    m: 0.5,
    pH: 8.0,
    contactTime: 60,
    adsorbentDose: 5.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Rice Husk',
    agent: 'H₃PO₄',
    activationTemp: 600,
    activationTime: 90,
  },
  {
    id: 5,
    C0: 100,
    Ce: 15.0,
    V: 150,
    m: 1.0,
    pH: 5.5,
    contactTime: 75,
    adsorbentDose: 6.7,
    pollutant: 'Methylene Blue',
    wasteType: 'Rice Husk',
    agent: 'KOH',
    activationTemp: 650,
    activationTime: 100,
  },
  {
    id: 6,
    C0: 200,
    Ce: 30.0,
    V: 100,
    m: 1.0,
    pH: 6.0,
    contactTime: 120,
    adsorbentDose: 10.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Sawdust',
    agent: 'H₃PO₄',
    activationTemp: 550,
    activationTime: 60,
  },
  {
    id: 7,
    C0: 50,
    Ce: 4.5,
    V: 100,
    m: 0.5,
    pH: 6.5,
    contactTime: 60,
    adsorbentDose: 5.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Coconut Shell',
    agent: 'KOH',
    activationTemp: 750,
    activationTime: 150,
  },
  {
    id: 8,
    C0: 250,
    Ce: 42.5,
    V: 100,
    m: 1.5,
    pH: 7.0,
    contactTime: 90,
    adsorbentDose: 15.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Coconut Shell',
    agent: 'KOH',
    activationTemp: 700,
    activationTime: 120,
  },
  {
    id: 9,
    C0: 75,
    Ce: 11.25,
    V: 100,
    m: 0.75,
    pH: 5.0,
    contactTime: 45,
    adsorbentDose: 7.5,
    pollutant: 'Methylene Blue',
    wasteType: 'Coconut Shell',
    agent: 'KOH',
    activationTemp: 700,
    activationTime: 120,
  },
  {
    id: 10,
    C0: 300,
    Ce: 55.0,
    V: 100,
    m: 1.0,
    pH: 8.0,
    contactTime: 60,
    adsorbentDose: 10.0,
    pollutant: 'Methylene Blue',
    wasteType: 'Sugarcane Bagasse',
    agent: 'H₃PO₄',
    activationTemp: 500,
    activationTime: 90,
  },
];

export const DEMO_WASTE_SELECTION = {
  wasteType: 'Coconut Shell',
  agent: 'KOH',
  activationTemp: 700,
  activationTime: 120,
};
